/-!
# FunctorFlowProofs.Limits

Machine-checked certification of (co)limits of finite `Set`-valued diagrams —
i.e. the Kan extensions along the terminal functor (`Σ_! = colimit`,
`Π_! = limit`). A diagram is emitted as a `SetDiagram` (objects with their
finite element sets, and edges as element-level maps); a colimit/limit instance
adds its cocone/cone, and the decidable `isColimit` / `isLimit` predicates
encode the universal property:

* a **colimit** is the quotient of `⊔ X(c)` by the connected-component relation
  generated by the edges — so `isColimit` checks the cocone commutes, is jointly
  surjective, and identifies two elements *iff* they lie in the same component;
* a **limit** is the set of compatible families — so `isLimit` checks the cone
  commutes and the projections give a bijection onto the compatible families.

Both are decidable, so a certificate proves `… = true` by `native_decide`.
-/

namespace FunctorFlowProofs

structure SetEdge where
  src : String
  tgt : String
  map : List (String × String)        -- X(f) : X(src) → X(tgt), element ↦ image
deriving Repr

structure SetDiagram where
  objs : List String
  sets : List (String × List String)  -- object ↦ its elements
  edges : List SetEdge
deriving Repr

def assoc? (l : List (String × String)) (k : String) : Option String :=
  (l.find? (·.1 == k)).map (·.2)

def SetDiagram.setOf (d : SetDiagram) (o : String) : List String :=
  (d.sets.find? (·.1 == o)).elim [] (·.2)

def SetDiagram.tagged (d : SetDiagram) : List (String × String) :=
  d.sets.bind (fun p => p.2.map (fun e => (p.1, e)))

/-! ## Colimit -/

structure ColimitCert where
  diagram : SetDiagram
  apex : List String
  legs : List (String × List (String × String))   -- object ↦ (element ↦ apex element)
deriving Repr

def ColimitCert.legApp (c : ColimitCert) (o x : String) : Option String :=
  match c.legs.find? (·.1 == o) with
  | some p => assoc? p.2 x
  | none => none

private def idxOf (tagged : List (String × String)) (t : String × String) : Nat :=
  (tagged.findIdx? (· == t)).getD 0

private def edgePairs (d : SetDiagram) (tagged : List (String × String)) : List (Nat × Nat) :=
  d.edges.bind (fun e =>
    e.map.map (fun pr => (idxOf tagged (e.src, pr.1), idxOf tagged (e.tgt, pr.2))))

-- connected-component labels of the tagged elements under the edge relation
private def components (n : Nat) (pairs : List (Nat × Nat)) : Array Nat := Id.run do
  let mut lbl : Array Nat := Array.range n
  for _ in [0:n] do
    for p in pairs do
      let a := lbl[p.1]!
      let b := lbl[p.2]!
      let m := Nat.min a b
      lbl := lbl.set! p.1 m
      lbl := lbl.set! p.2 m
  return lbl

/-- Decidable colimit check: the cocone commutes, is jointly surjective, and
two diagram elements share an apex image *iff* they are connected. -/
def ColimitCert.isColimit (c : ColimitCert) : Bool :=
  let tagged := c.diagram.tagged
  let n := tagged.length
  let lbl := components n (edgePairs c.diagram tagged)
  -- cocone commutes
  (c.diagram.edges.all (fun e =>
    e.map.all (fun pr => c.legApp e.src pr.1 == c.legApp e.tgt pr.2))) &&
  -- jointly surjective onto the apex
  (c.apex.all (fun a => tagged.any (fun t => c.legApp t.1 t.2 == some a))) &&
  -- apex identifications are exactly the connected components
  ((List.range n).all (fun i => (List.range n).all (fun j =>
    let ti := tagged[i]!; let tj := tagged[j]!
    (c.legApp ti.1 ti.2 == c.legApp tj.1 tj.2) == (lbl[i]! == lbl[j]!))))

def ColimitCert.IsColimit (c : ColimitCert) : Prop := c.isColimit = true
theorem ColimitCert.isColimit_sound {c : ColimitCert} (h : c.isColimit = true) : c.IsColimit := h

/-! ## Limit -/

structure LimitCert where
  diagram : SetDiagram
  apex : List String
  legs : List (String × List (String × String))   -- object ↦ (apex element ↦ X(object) element)
deriving Repr

def LimitCert.legApp (c : LimitCert) (o a : String) : Option String :=
  match c.legs.find? (·.1 == o) with
  | some p => assoc? p.2 a
  | none => none

private def naryProduct : List (List String) → List (List String)
  | [] => [[]]
  | x :: xs => (naryProduct xs).bind (fun rest => x.map (fun a => a :: rest))

private def famVal (objs : List String) (fam : List String) (o : String) : String :=
  match objs.findIdx? (· == o) with
  | some i => fam[i]!
  | none => ""

private def SetDiagram.compatibleFamilies (d : SetDiagram) : List (List String) :=
  (naryProduct (d.objs.map d.setOf)).filter (fun fam =>
    d.edges.all (fun e =>
      assoc? e.map (famVal d.objs fam e.src) == some (famVal d.objs fam e.tgt)))

/-- Decidable limit check: the cone commutes and the projections give a
bijection between the apex and the compatible families. -/
def LimitCert.isLimit (c : LimitCert) : Bool :=
  let objs := c.diagram.objs
  let proj := fun a => objs.map (fun o => (c.legApp o a).getD "")
  let fams := c.diagram.compatibleFamilies
  -- cone commutes
  (c.diagram.edges.all (fun e =>
    c.apex.all (fun a =>
      assoc? e.map ((c.legApp e.src a).getD "") == some ((c.legApp e.tgt a).getD "")))) &&
  -- projections land in compatible families, injectively, and surject onto them
  (c.apex.all (fun a => (c.apex.map proj).count (proj a) == 1)) &&
  (c.apex.all (fun a => (fams.find? (· == proj a)).isSome)) &&
  (c.apex.length == fams.length)

def LimitCert.IsLimit (c : LimitCert) : Prop := c.isLimit = true
theorem LimitCert.isLimit_sound {c : LimitCert} (h : c.isLimit = true) : c.IsLimit := h

end FunctorFlowProofs
