# ============================================================================
# presented.jl — finitely-presented categories (free category + relations)
# (included into module Cat)
#
# A `FinPresentedCat` is the free category on a finite DAG quotiented by a
# congruence generated by *relations* — declared equalities between parallel
# paths. Hom-sets are equivalence classes of paths (each carried by a canonical
# representative), so commuting diagrams (e.g. a commutative square) become
# genuine categories, not just shapes. Congruence closure is computed by
# enumeration (finite, by acyclicity).
# ============================================================================

"""
    FinPresentedCat(objects, edges, relations)

The free category on the DAG `(objects, edges)` modulo the congruence
generated by `relations` (a list of `(path₁, path₂)` parallel `PathMor`s
declared equal). Morphisms are congruence classes, represented canonically;
`compose`/`id`/`homset` work on representatives.
"""
struct FinPresentedCat <: AbstractCategory
    objects::Vector{Symbol}
    edges::Vector{Tuple{Symbol, Symbol, Symbol}}
    relations::Vector{Tuple{PathMor, PathMor}}
    rep::Dict{PathMor, PathMor}     # every path ↦ its class representative
end

function FinPresentedCat(objects, edges, relations)
    free = FreeCat(objects, edges)
    rels = Tuple{PathMor, PathMor}[]
    for (p, q) in relations
        (p.dom == q.dom && p.cod == q.cod) ||
            throw(ArgumentError("relation $(p) = $(q) is not between parallel morphisms"))
        push!(rels, (p, q))
    end
    rep = _congruence(free, rels)
    FinPresentedCat(free.objects, free.edges, rels, rep)
end

"""Lexicographic order on paths: shorter first, then by edge-name sequence."""
_path_lt(a::PathMor, b::PathMor) = (length(a.edges), a.edges) < (length(b.edges), b.edges)

# Congruence closure over the (finite) set of all paths of `free`.
function _congruence(free::FreeCat, relations::Vector{Tuple{PathMor,PathMor}})
    allpaths = PathMor[]
    for a in free.objects, b in free.objects
        append!(allpaths, homset(free, a, b))
    end
    idx = Dict{PathMor, Int}(p => i for (i, p) in enumerate(allpaths))
    parent = collect(1:length(allpaths))
    find(i) = (while parent[i] != i; parent[i] = parent[parent[i]]; i = parent[i]; end; i)
    unite!(p, q) = begin
        ri, rj = find(idx[p]), find(idx[q])
        ri == rj ? false : (parent[ri] = rj; true)
    end

    for (p, q) in relations
        haskey(idx, p) && haskey(idx, q) ||
            throw(ArgumentError("relation path is not a valid path of the free category"))
        unite!(p, q)
    end

    # all prefixes into a given object and suffixes out of a given object
    prefixes(a) = vcat((homset(free, x, a) for x in free.objects)...)
    suffixes(b) = vcat((homset(free, b, y) for y in free.objects)...)

    changed = true
    while changed
        changed = false
        n = length(allpaths)
        for i in 1:n, j in (i+1):n
            find(i) == find(j) || continue
            p, q = allpaths[i], allpaths[j]
            (p.dom == q.dom && p.cod == q.cod) || continue
            for r in prefixes(p.dom), s in suffixes(p.cod)
                rp = compose(free, compose(free, r, p), s)
                rq = compose(free, compose(free, r, q), s)
                unite!(rp, rq) && (changed = true)
            end
        end
    end

    classes = Dict{Int, Vector{PathMor}}()
    for (p, i) in idx
        push!(get!(classes, find(i), PathMor[]), p)
    end
    rep = Dict{PathMor, PathMor}()
    for ps in values(classes)
        r = reduce((a, b) -> _path_lt(a, b) ? a : b, ps)
        for p in ps
            rep[p] = r
        end
    end
    rep
end

# ---- interface ----

Base.:(==)(a::FinPresentedCat, b::FinPresentedCat) =
    a.objects == b.objects && a.edges == b.edges && a.relations == b.relations

objects(C::FinPresentedCat) = copy(C.objects)
ob(C::FinPresentedCat) = objects(C)
dom(::FinPresentedCat, f::PathMor) = f.dom
cod(::FinPresentedCat, f::PathMor) = f.cod

"""Normalise a path to its congruence-class representative."""
normalize(C::FinPresentedCat, p::PathMor) = get(C.rep, p, p)

id(C::FinPresentedCat, a) = normalize(C, PathMor(Symbol(a), Symbol(a), Symbol[]))

function compose(C::FinPresentedCat, f::PathMor, g::PathMor)
    f.cod == g.dom || throw(ArgumentError("not composable: cod $(f.cod) ≠ dom $(g.dom)"))
    normalize(C, PathMor(f.dom, g.cod, vcat(f.edges, g.edges)))
end

"""`homset(C, a, b)` — the congruence classes `a → b`, as canonical reps."""
function homset(C::FinPresentedCat, a, b)
    a = Symbol(a); b = Symbol(b)
    reps = PathMor[]
    seen = Set{PathMor}()
    # enumerate free paths, collapse to reps
    for p in _free_homset(C, a, b)
        r = normalize(C, p)
        r in seen || (push!(seen, r); push!(reps, r))
    end
    reps
end

# free paths a→b (without quotient), reusing the FreeCat enumeration
function _free_homset(C::FinPresentedCat, a::Symbol, b::Symbol)
    adj = Dict{Symbol, Vector{Tuple{Symbol,Symbol}}}()
    for (n, s, t) in C.edges
        push!(get!(adj, s, Tuple{Symbol,Symbol}[]), (n, t))
    end
    out = PathMor[]
    function dfs(cur, path)
        cur == b && push!(out, PathMor(a, b, copy(path)))
        for (n, t) in get(adj, cur, Tuple{Symbol,Symbol}[])
            push!(path, n); dfs(t, path); pop!(path)
        end
    end
    dfs(a, Symbol[])
    out
end

hom_cardinality(C::FinPresentedCat, a, b) = length(homset(C, a, b))

# ---- standard example ----

"""
    commutative_square() -> FinPresentedCat

The commutative square `a →f→ b →h→ d`, `a →g→ c →k→ d` with `f·h = g·k`.
Unlike the *free* diamond, `Hom(a, d)` is a single morphism — the square
commutes — so `a` is genuinely initial.
"""
function commutative_square()
    objs = [:a, :b, :c, :d]
    edges = [(:f, :a, :b), (:g, :a, :c), (:h, :b, :d), (:k, :c, :d)]
    fh = PathMor(:a, :d, [:f, :h])
    gk = PathMor(:a, :d, [:g, :k])
    FinPresentedCat(objs, edges, [(fh, gk)])
end
