# ============================================================================
# cat_certificates.jl — emit Lean certificates for the Cat kernel
#
# Turns a finite `Cat.FreeCat` / `Cat.FinPresentedCat` into a `CatTable` and a
# `Cat.FinFunctor` into a `FunctorDecl` (see proofs/FunctorFlowProofs/Cat.lean),
# with a `native_decide` proof that the category / functor laws hold — a
# machine-checked counterpart to the kernel's runtime enumeration checks.
# Reuses `lean_string` / `lean_list` from `proof_interface.jl`.
# ============================================================================

# All morphisms (class representatives) of a finite category, deduplicated.
function _cat_morphisms(C)
    objs = Cat.objects(C)
    mors = Cat.PathMor[]
    seen = Set{Cat.PathMor}()
    for a in objs, b in objs, m in Cat.homset(C, a, b)
        m in seen || (push!(mors, m); push!(seen, m))
    end
    mors
end

# Emit the `CatTable` record literal for a finite category + the name map.
function _cat_table_literal(C)
    objs = Cat.objects(C)
    mors = _cat_morphisms(C)
    name = Dict{Cat.PathMor, String}()
    for (i, m) in enumerate(mors)
        name[m] = "m$(i - 1)"
    end
    obj_lit = lean_list([lean_string(string(o)) for o in objs])
    mor_lit = lean_list([
        "{ name := $(lean_string(name[m])), dom := $(lean_string(string(m.dom))), cod := $(lean_string(string(m.cod))) }"
        for m in mors])
    comp_entries = String[]
    for f in mors, g in mors
        f.cod == g.dom || continue
        h = Cat.compose(C, f, g)
        push!(comp_entries,
            "($(lean_string(name[f])), $(lean_string(name[g])), $(lean_string(name[h])))")
    end
    comp_lit = lean_list(comp_entries)
    id_lit = lean_list([
        "($(lean_string(string(o))), $(lean_string(name[Cat.id(C, o)])))" for o in objs])
    table = "{ objects := $obj_lit, morphisms := $mor_lit, comp := $comp_lit, ids := $id_lit }"
    (table, name)
end

"""
    render_cat_certificate(C; module_name=nothing) -> String

Emit a Lean certificate that a finite category `C` (`Cat.FreeCat` or
`Cat.FinPresentedCat`) satisfies the category axioms, proved by `native_decide`.
"""
function render_cat_certificate(C; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? "CatCert" : module_name
    table, _ = _cat_table_literal(C)
    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (Cat kernel certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def exportedCat : CatTable := $table")
    push!(lines, "")
    push!(lines, "theorem exportedCat_isCategory : exportedCat.isCategory = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end

"""
    render_functor_certificate(F::Cat.FinFunctor; module_name=nothing) -> String

Emit a Lean certificate that a finite functor `F` satisfies the functor laws
(and that its domain/codomain are categories), proved by `native_decide`.
"""
function render_functor_certificate(F::Cat.FinFunctor; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? "FunctorCert" : module_name
    domtab, dname = _cat_table_literal(F.dom)
    codtab, cname = _cat_table_literal(F.cod)
    ob_lit = lean_list([
        "($(lean_string(string(o))), $(lean_string(string(F.ob_map[o]))))" for o in Cat.objects(F.dom)])
    mor_entries = String[]
    for p in _cat_morphisms(F.dom)
        Fp = F(p)
        push!(mor_entries, "($(lean_string(dname[p])), $(lean_string(cname[Fp])))")
    end
    mor_lit = lean_list(mor_entries)

    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (Cat functor certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def domCat : CatTable := $domtab")
    push!(lines, "def codCat : CatTable := $codtab")
    push!(lines, "")
    push!(lines, "def exportedFunctor : FunctorDecl :=")
    push!(lines, "  { dom := domCat, cod := codCat, obMap := $ob_lit, morMap := $mor_lit }")
    push!(lines, "")
    push!(lines, "theorem domCat_isCategory : domCat.isCategory = true := by native_decide")
    push!(lines, "theorem codCat_isCategory : codCat.isCategory = true := by native_decide")
    push!(lines, "theorem exportedFunctor_isFunctor : exportedFunctor.isFunctor = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end

# obMap / morMap record fields for a functor, given its (co)domain name maps.
function _functor_maps(F, dname, cname)
    ob_lit = lean_list([
        "($(lean_string(string(o))), $(lean_string(string(F.ob_map[o]))))" for o in Cat.objects(F.dom)])
    mor_lit = lean_list([
        "($(lean_string(dname[p])), $(lean_string(cname[F(p)])))" for p in _cat_morphisms(F.dom)])
    (ob_lit, mor_lit)
end

# component list (object ↦ morphism name) for a nat-transformation over `cat`.
_component_list(comps, cat, namemap) = lean_list([
    "($(lean_string(string(o))), $(lean_string(namemap[comps[o]])))" for o in Cat.objects(cat)])

"""
    render_adjunction_certificate(adj::Cat.Adjunction; module_name=nothing) -> String

Emit a Lean certificate that `adj` is an adjunction (both functors are functors
and both triangle identities hold), proved by `native_decide`.
"""
function render_adjunction_certificate(adj::Cat.Adjunction; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? "AdjCert" : module_name
    F, G = adj.left, adj.right
    Cobj, Dobj = F.dom, F.cod
    catC, nameC = _cat_table_literal(Cobj)
    catD, nameD = _cat_table_literal(Dobj)
    Fob, Fmor = _functor_maps(F, nameC, nameD)
    Gob, Gmor = _functor_maps(G, nameD, nameC)
    unit_lit = _component_list(adj.unit.components, Cobj, nameC)
    counit_lit = _component_list(adj.counit.components, Dobj, nameD)
    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (Cat adjunction certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def catC : CatTable := $catC")
    push!(lines, "def catD : CatTable := $catD")
    push!(lines, "def leftFun : FunctorDecl := { dom := catC, cod := catD, obMap := $Fob, morMap := $Fmor }")
    push!(lines, "def rightFun : FunctorDecl := { dom := catD, cod := catC, obMap := $Gob, morMap := $Gmor }")
    push!(lines, "def exportedAdjunction : AdjunctionDecl :=")
    push!(lines, "  { F := leftFun, G := rightFun, unit := $unit_lit, counit := $counit_lit }")
    push!(lines, "")
    push!(lines, "theorem exportedAdjunction_isAdjunction : exportedAdjunction.isAdjunction = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end

# Emit a `SetDiagram` literal for a Set-valued functor X : C → FinSet.
function _set_diagram_literal(X::Cat.SetFunctor)
    C = X.cat
    es(x) = lean_string(string(x))
    objs_lit = lean_list([es(o) for o in Cat.objects(C)])
    sets_lit = lean_list([
        "($(es(o)), $(lean_list([es(e) for e in Cat.ob(X, o).elements])))" for o in Cat.objects(C)])
    edge_lits = String[]
    for (n, s, t) in C.edges
        f = X.edge_map[n]
        mp = lean_list(["($(es(x)), $(es(f(x))))" for x in Cat.ob(X, s).elements])
        push!(edge_lits, "{ src := $(es(s)), tgt := $(es(t)), map := $mp }")
    end
    "{ objs := $objs_lit, sets := $sets_lit, edges := $(lean_list(edge_lits)) }"
end

"""
    render_heyting_certificate(H::Cat.HeytingAlgebra; module_name=nothing) -> String

Emit a Lean certificate that `H` is a Heyting algebra (the adjunction
`z∧x ≤ y ⇔ z ≤ (x⇒y)`), proved by `native_decide`.
"""
function render_heyting_certificate(H::Cat.HeytingAlgebra; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? "HeytingCert" : module_name
    es(x) = lean_string(string(x))
    elems = lean_list([es(x) for x in H.elements])
    leq = lean_list(["(($(es(x)), $(es(y))), $(Cat.hle(H, x, y)))" for x in H.elements for y in H.elements])
    meet = lean_list(["(($(es(x)), $(es(y))), $(es(Cat.hmeet(H, x, y))))" for x in H.elements for y in H.elements])
    imply = lean_list(["(($(es(x)), $(es(y))), $(es(Cat.himply(H, x, y))))" for x in H.elements for y in H.elements])
    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (Heyting-algebra certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def exportedHeyting : HeytingDecl :=")
    push!(lines, "  { elements := $elems, leq := $leq, meet := $meet, imply := $imply }")
    push!(lines, "")
    push!(lines, "theorem exportedHeyting_isHeyting : exportedHeyting.isHeyting = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end

"""
    render_galois_certificate(P, Q, f, g; module_name=nothing) -> String

Emit a Lean certificate that `(f, g)` is a Galois connection between posets
`P`, `Q` (`f(p) ≤ q ⇔ p ≤ g(q)`), proved by `native_decide`.
"""
function render_galois_certificate(P::Cat.Poset, Q::Cat.Poset, f::AbstractDict, g::AbstractDict;
                                   module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? "GaloisCert" : module_name
    es(x) = lean_string(string(x))
    Pl = lean_list([es(x) for x in P.elements]); Ql = lean_list([es(x) for x in Q.elements])
    pleq = lean_list(["(($(es(x)), $(es(y))), $(Cat.ple(P, x, y)))" for x in P.elements for y in P.elements])
    qleq = lean_list(["(($(es(x)), $(es(y))), $(Cat.ple(Q, x, y)))" for x in Q.elements for y in Q.elements])
    fl = lean_list(["($(es(p)), $(es(f[p])))" for p in P.elements])
    gl = lean_list(["($(es(q)), $(es(g[q])))" for q in Q.elements])
    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (Galois-connection certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def exportedGalois : GaloisDecl :=")
    push!(lines, "  { P := $Pl, Q := $Ql, pleq := $pleq, qleq := $qleq, f := $fl, g := $gl }")
    push!(lines, "")
    push!(lines, "theorem exportedGalois_isGalois : exportedGalois.isGalois = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end

"""
    render_metric_certificate(M::Cat.MetricCat; module_name=nothing) -> String

Emit a Lean certificate that `M` is a Lawvere metric space (a category enriched
over the cost quantale — identity + triangle inequality), proved by `native_decide`.
"""
function render_metric_certificate(M::Cat.MetricCat; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? "MetricCert" : module_name
    es(x) = lean_string(string(x))
    pts = lean_list([es(p) for p in M.points])
    dist = lean_list(["(($(es(x)), $(es(y))), $(Cat.metric_dist(M, x, y)))" for x in M.points for y in M.points])
    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (enriched/metric certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def exportedMetric : MetricDecl := { points := $pts, dist := $dist }")
    push!(lines, "")
    push!(lines, "theorem exportedMetric_isLawvere : exportedMetric.isLawvereMetric = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end

"""
    render_lens_certificate(l::Cat.Lens; module_name=nothing) -> String

Emit a Lean certificate that the lens `l` is very-well-behaved (GetPut, PutGet,
PutPut), proved by `native_decide`.
"""
function render_lens_certificate(l::Cat.Lens; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? "LensCert" : module_name
    es(x) = lean_string(string(x))
    Sl = lean_list([es(s) for s in l.S])
    Al = lean_list([es(a) for a in l.A])
    getl = lean_list(["($(es(s)), $(es(l.get(s))))" for s in l.S])
    putl = lean_list(["(($(es(s)), $(es(a))), $(es(l.put((s, a)))))" for s in l.S for a in l.A])
    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (lens-law certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def exportedLens : LensDecl := { S := $Sl, A := $Al, get := $getl, put := $putl }")
    push!(lines, "")
    push!(lines, "theorem exportedLens_veryWellBehaved : exportedLens.veryWellBehaved = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end

# Emit a MooreDecl literal for a Cat.MooreMachine.
function _moore_literal(M::Cat.MooreMachine)
    es(x) = lean_string(string(x))
    st = lean_list([es(s) for s in M.states])
    ins = lean_list([es(i) for i in M.inputs])
    trans = lean_list([
        "(($(es(s)), $(es(i))), $(es(M.transition[(s, i)])))" for s in M.states for i in M.inputs])
    out = lean_list(["($(es(s)), $(es(M.output[s])))" for s in M.states])
    "{ states := $st, inputs := $ins, transition := $trans, output := $out }"
end

"""
    render_bisimulation_certificate(M::Cat.MooreMachine, R; module_name=nothing) -> String

Emit a Lean certificate that `R` is a bisimulation of the Moore machine `M`
(behavioural equivalence), proved by `native_decide`.
"""
function render_bisimulation_certificate(M::Cat.MooreMachine, R; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? "BisimCert" : module_name
    Rlit = lean_list(["($(lean_string(string(a))), $(lean_string(string(b))))" for (a, b) in R])
    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (bisimulation certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def exportedMoore : MooreDecl := $(_moore_literal(M))")
    push!(lines, "")
    push!(lines, "theorem exportedMoore_isBisimulation :")
    push!(lines, "    exportedMoore.isBisimulation $Rlit = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end

_nat_matrix_literal(M::AbstractMatrix) =
    "[" * join(["[" * join(M[i, :], ", ") * "]" for i in 1:size(M, 1)], ", ") * "]"

"""
    render_backprop_certificate(f::Cat.LinMap, g::Cat.LinMap; module_name=nothing) -> String

Emit a Lean certificate that **backprop is functorial** for the composite of two
layers `f`, `g` over ℤ_n: `(g∘f)ᵀ = fᵀ∘gᵀ` (the chain rule), proved by
`native_decide`. This is the categorical-deep-learning law made machine-checked.
"""
function render_backprop_certificate(f::Cat.LinMap, g::Cat.LinMap; module_name::Union{Nothing, String}=nothing)
    f.modulus == g.modulus || throw(ArgumentError("layers must share a modulus"))
    f.outdim == g.indim || throw(ArgumentError("layers not composable"))
    mod = module_name === nothing ? "BackpropCert" : module_name
    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (backprop-as-functor certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def Fmat : List (List Nat) := $(_nat_matrix_literal(f.matrix))")
    push!(lines, "def Gmat : List (List Nat) := $(_nat_matrix_literal(g.matrix))")
    push!(lines, "")
    push!(lines, "-- (g ∘ f)ᵀ = fᵀ ∘ gᵀ  : backpropagation reverses the network (the chain rule)")
    push!(lines, "theorem backprop_chain_rule : chainRuleHolds $(f.modulus) Fmat Gmat = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end

"""
    render_colimit_certificate(col::Cat.ColimitCocone; module_name=nothing) -> String

Emit a Lean certificate that `col` is the colimit of its diagram (cocone
commutes, jointly surjective, identifications = connected components), proved by
`native_decide`. This certifies the Kan extension `Σ_!` (colimit) law.
"""
function render_colimit_certificate(col::Cat.ColimitCocone; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? "ColimitCert" : module_name
    X = col.functor
    es(x) = lean_string(string(x))
    apex_lit = lean_list([es(a) for a in col.apex.elements])
    legs_lit = lean_list([
        "($(es(o)), $(lean_list(["($(es(x)), $(es(col.legs[o](x))))" for x in Cat.ob(X, o).elements])))"
        for o in Cat.objects(X.cat)])
    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (colimit certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def exportedColimit : ColimitCert :=")
    push!(lines, "  { diagram := $(_set_diagram_literal(X)), apex := $apex_lit, legs := $legs_lit }")
    push!(lines, "")
    push!(lines, "theorem exportedColimit_isColimit : exportedColimit.isColimit = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end

"""
    render_limit_certificate(lim::Cat.LimitCone; module_name=nothing) -> String

Emit a Lean certificate that `lim` is the limit of its diagram (cone commutes,
projections biject onto the compatible families), proved by `native_decide`.
This certifies the Kan extension `Π_!` (limit) law.
"""
function render_limit_certificate(lim::Cat.LimitCone; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? "LimitCert" : module_name
    X = lim.functor
    es(x) = lean_string(string(x))
    apex_lit = lean_list([es(a) for a in lim.apex.elements])
    legs_lit = lean_list([
        "($(es(o)), $(lean_list(["($(es(a)), $(es(lim.legs[o](a))))" for a in lim.apex.elements])))"
        for o in Cat.objects(X.cat)])
    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (limit certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def exportedLimit : LimitCert :=")
    push!(lines, "  { diagram := $(_set_diagram_literal(X)), apex := $apex_lit, legs := $legs_lit }")
    push!(lines, "")
    push!(lines, "theorem exportedLimit_isLimit : exportedLimit.isLimit = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end

"""
    render_monad_certificate(m::Cat.Monad; module_name=nothing) -> String

Emit a Lean certificate that `m` is a monad (functor + unit and associativity
laws), proved by `native_decide`.
"""
function render_monad_certificate(m::Cat.Monad; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? "MonadCert" : module_name
    T = m.functor
    Cobj = T.dom
    catC, nameC = _cat_table_literal(Cobj)
    Tob, Tmor = _functor_maps(T, nameC, nameC)
    unit_lit = _component_list(m.unit.components, Cobj, nameC)
    mult_lit = _component_list(m.mult.components, Cobj, nameC)
    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl (Cat monad certificate)")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "open FunctorFlowProofs")
    push!(lines, "")
    push!(lines, "def catC : CatTable := $catC")
    push!(lines, "def endoFun : FunctorDecl := { dom := catC, cod := catC, obMap := $Tob, morMap := $Tmor }")
    push!(lines, "def exportedMonad : MonadDecl := { T := endoFun, unit := $unit_lit, mult := $mult_lit }")
    push!(lines, "")
    push!(lines, "theorem exportedMonad_isMonad : exportedMonad.isMonad = true := by native_decide")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")
    join(lines, "\n")
end
