# ============================================================================
# proof_interface.jl — Lean 4 certificate generation
# ============================================================================

"""
    diagram_certificate_payload(D::Diagram) -> Dict

Generate a certificate payload from a diagram for Lean proof verification.
"""
function diagram_certificate_payload(D::Diagram)
    ir = to_ir(D)
    Dict{String, Any}(
        "diagram_name" => String(ir.name),
        "objects" => [String(o.name) for o in ir.objects],
        "operations" => [
            let
                kind_str, refs = _operation_decl(op)
                Dict{String, Any}(
                    "name" => get(op, :name, ""),
                    "kind" => kind_str,
                    "refs" => refs,
                )
            end
            for op in ir.operations
        ],
        "ports" => [
            Dict{String, Any}(
                "name" => String(p.name),
                "ref" => String(p.ref),
                "kind" => String(p.kind),
                "port_type" => String(p.port_type),
                "direction" => lowercase(string(p.direction)),
            )
            for p in ir.ports
        ],
    )
end

function _operation_decl(op::Dict{Symbol, Any})
    kind = op[:kind]
    if kind == :morphism
        ("OperationKind.morphism", [String(op[:source]), String(op[:target])])
    elseif kind == :composition
        refs = String.(op[:chain])
        push!(refs, String(op[:source]))
        push!(refs, String(op[:target]))
        ("OperationKind.composition", refs)
    elseif kind == :kanextension
        dir = op[:direction]
        kind_str = dir == :left ? "OperationKind.leftKan" : "OperationKind.rightKan"
        refs = [String(op[:source]), String(op[:along])]
        op[:target] !== nothing && push!(refs, String(op[:target]))
        (kind_str, refs)
    else
        ("OperationKind.unknown", String[])
    end
end

"""
    render_lean_certificate(D::Diagram; module_name=nothing) -> String

Generate Lean 4 source code for a diagram certificate.
"""
function render_lean_certificate(D::Diagram; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? _sanitize_module_name(String(D.name)) : module_name
    payload = diagram_certificate_payload(D)

    lines = String[]
    push!(lines, "-- Auto-generated by FunctorFlow.jl")
    push!(lines, "namespace FunctorFlowProofs.Generated.$mod")
    push!(lines, "")
    push!(lines, "open FunctorFlowProofs in")
    push!(lines, "")

    # DiagramDecl
    push!(lines, "def exportedDiagram : DiagramDecl := {")
    push!(lines, "  name := $(lean_string(payload["diagram_name"])),")
    push!(lines, "  objects := $(lean_list([lean_string(o) for o in payload["objects"]])),")

    op_strs = String[]
    for op in payload["operations"]
        refs_str = lean_list([lean_string(r) for r in op["refs"]])
        push!(op_strs, "{ name := $(lean_string(op["name"])), kind := $(op["kind"]), refs := $refs_str }")
    end
    push!(lines, "  operations := $(lean_list(op_strs)),")

    port_strs = String[]
    for p in payload["ports"]
        push!(port_strs, "{ name := $(lean_string(p["name"])), ref := $(lean_string(p["ref"])), kind := $(lean_string(p["kind"])), portType := $(lean_string(p["port_type"])), direction := $(lean_string(p["direction"])) }")
    end
    push!(lines, "  ports := $(lean_list(port_strs))")
    push!(lines, "}")
    push!(lines, "")

    # Lowering artifact
    push!(lines, "def exportedArtifact : LoweringArtifact := {")
    push!(lines, "  diagram := exportedDiagram,")
    push!(lines, "  resolvedRefs := true,")
    push!(lines, "  portsClosed := true")
    push!(lines, "}")
    push!(lines, "")

    # Theorems
    push!(lines, "theorem exportedArtifact_checks : exportedArtifact.check = true := by native_decide")
    push!(lines, "")
    push!(lines, "theorem exportedArtifact_sound : exportedArtifact.Sound :=")
    push!(lines, "  LoweringArtifact.sound_of_check exportedArtifact_checks")
    push!(lines, "")
    push!(lines, "end FunctorFlowProofs.Generated.$mod")

    join(lines, "\n")
end

"""
    render_construction_certificate(uc::UniversalConstruction; module_name=nothing) -> String

Generate a Lean 4 certificate that declares and verifies a universal construction.
Includes the construction type, participating diagrams, and structural theorems.
"""
function render_construction_certificate(uc::PullbackResult; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? _sanitize_module_name(String(uc.name)) : module_name
    base_cert = render_lean_certificate(uc.cone; module_name=mod)

    # Insert construction declaration before the closing namespace
    construction_lines = String[]
    push!(construction_lines, "")
    push!(construction_lines, "-- Pullback construction declaration")
    push!(construction_lines, "def pullbackDecl : ConstructionDecl := {")
    push!(construction_lines, "  kind := ConstructionKind.pullback,")
    push!(construction_lines, "  diagram := exportedDiagram,")
    push!(construction_lines, "  projection1 := $(lean_string(String(uc.projection1))),")
    push!(construction_lines, "  projection2 := $(lean_string(String(uc.projection2))),")
    push!(construction_lines, "  sharedObject := $(lean_string(String(uc.shared_object))),")
    push!(construction_lines, "  interfaceMorphisms := $(lean_list([lean_string(String(m)) for m in uc.interface_morphisms]))")
    push!(construction_lines, "}")
    push!(construction_lines, "")
    push!(construction_lines, "-- Commuting square theorem: both projections agree on shared interface")
    push!(construction_lines, "theorem pullback_commutes : pullbackDecl.CommutingSquare := by")
    push!(construction_lines, "  exact ConstructionDecl.commuting_of_loss exportedArtifact")
    push!(construction_lines, "")

    # Insert before the end namespace line
    lines = split(base_cert, "\n")
    insert_idx = findlast(l -> startswith(l, "end "), lines)
    if insert_idx !== nothing
        result_lines = vcat(lines[1:insert_idx-1], construction_lines, [lines[insert_idx]])
        join(result_lines, "\n")
    else
        base_cert * "\n" * join(construction_lines, "\n")
    end
end

function render_construction_certificate(uc::PushoutResult; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? _sanitize_module_name(String(uc.name)) : module_name
    base_cert = render_lean_certificate(uc.cocone; module_name=mod)

    construction_lines = String[]
    push!(construction_lines, "")
    push!(construction_lines, "-- Pushout construction declaration")
    push!(construction_lines, "def pushoutDecl : ConstructionDecl := {")
    push!(construction_lines, "  kind := ConstructionKind.pushout,")
    push!(construction_lines, "  diagram := exportedDiagram,")
    push!(construction_lines, "  injection1 := $(lean_string(String(uc.injection1))),")
    push!(construction_lines, "  injection2 := $(lean_string(String(uc.injection2))),")
    push!(construction_lines, "  sharedObject := $(lean_string(String(uc.shared_object))),")
    push!(construction_lines, "  interfaceMorphisms := $(lean_list([lean_string(String(m)) for m in uc.interface_morphisms]))")
    push!(construction_lines, "}")
    push!(construction_lines, "")

    lines = split(base_cert, "\n")
    insert_idx = findlast(l -> startswith(l, "end "), lines)
    if insert_idx !== nothing
        result_lines = vcat(lines[1:insert_idx-1], construction_lines, [lines[insert_idx]])
        join(result_lines, "\n")
    else
        base_cert * "\n" * join(construction_lines, "\n")
    end
end

function render_construction_certificate(uc::ProductResult; module_name::Union{Nothing, String}=nothing)
    render_lean_certificate(uc.product_diagram; module_name=module_name)
end

function render_construction_certificate(uc::CoproductResult; module_name::Union{Nothing, String}=nothing)
    render_lean_certificate(uc.coproduct_diagram; module_name=module_name)
end

function render_construction_certificate(uc::EqualizerResult; module_name::Union{Nothing, String}=nothing)
    render_lean_certificate(uc.equalizer_diagram; module_name=module_name)
end

function render_construction_certificate(uc::CoequalizerResult; module_name::Union{Nothing, String}=nothing)
    render_lean_certificate(uc.coequalizer_diagram; module_name=module_name)
end

"""
    write_lean_certificate(D::Diagram; module_name=nothing, output_dir=".") -> String

Write a Lean certificate file for the diagram. Returns the file path.
"""
function write_lean_certificate(D::Diagram;
                                module_name::Union{Nothing, String}=nothing,
                                output_dir::AbstractString=".")
    mod = module_name === nothing ? _sanitize_module_name(String(D.name)) : module_name
    content = render_lean_certificate(D; module_name=mod)
    path = joinpath(output_dir, "$mod.lean")
    mkpath(dirname(path))
    write(path, content)
    path
end

function _sanitize_module_name(name::String)
    parts = split(replace(name, r"[^a-zA-Z0-9_]" => "_"), "_"; keepempty=false)
    join(uppercasefirst.(parts))
end

lean_string(s::AbstractString) = "\"$(escape_string(s))\""
lean_string(s::Symbol) = lean_string(String(s))
lean_list(items::Vector) = isempty(items) ? "[]" : "[$(join(items, ", "))]"

# ============================================================================
# JEPA & Coalgebra certificate generation
# ============================================================================

"""
    render_jepa_certificate(D::Diagram; module_name=nothing) -> String

Generate a Lean 4 certificate for a JEPA diagram, including:
- Standard diagram certificate
- Coalgebra declarations
- JEPA prediction-as-obstruction theorems
- Bisimulation declarations (if present)
"""
function render_jepa_certificate(D::Diagram; module_name::Union{Nothing, String}=nothing)
    mod = module_name === nothing ? _sanitize_module_name(String(D.name)) : module_name
    base_cert = render_lean_certificate(D; module_name=mod)

    coalgebras = get_coalgebras(D)
    bisimulations = get_bisimulations(D)

    extra_lines = String[]

    # Coalgebra declarations
    if !isempty(coalgebras)
        push!(extra_lines, "")
        push!(extra_lines, "-- Coalgebra declarations")
        for (name, c) in coalgebras
            push!(extra_lines, "def coalgebra_$(name) : CoalgebraDecl := {")
            push!(extra_lines, "  name := $(lean_string(String(name))),")
            push!(extra_lines, "  state := $(lean_string(String(c.state))),")
            push!(extra_lines, "  transition := $(lean_string(String(c.transition))),")
            push!(extra_lines, "  functorType := $(lean_string(String(c.functor_type)))")
            push!(extra_lines, "}")
            push!(extra_lines, "")
        end
    end

    # JEPA-specific theorems
    jepa_losses = [l for l in values(D.losses)
                   if get(l.metadata, :macro, nothing) in (:JEPA, :KanJEPA)]
    if !isempty(jepa_losses)
        push!(extra_lines, "-- JEPA prediction-as-obstruction theorems")
        push!(extra_lines, "/-- The JEPA prediction loss is an obstruction to commutativity")
        push!(extra_lines, "    of the encoder/predictor square. When loss = 0, the square")
        push!(extra_lines, "    commutes and the encoder is an exact coalgebra morphism. -/")
        for loss in jepa_losses
            lname = String(loss.name)
            push!(extra_lines, "theorem jepa_$(lname)_is_obstruction :")
            push!(extra_lines, "    exportedArtifact.lossIsObstruction $(lean_string(lname)) := by")
            push!(extra_lines, "  exact LoweringArtifact.loss_obstruction_of_check exportedArtifact_checks")
            push!(extra_lines, "")
        end

        push!(extra_lines, "/-- When the JEPA prediction loss is zero, the encoder-predictor")
        push!(extra_lines, "    path commutes with the target encoder path, making the")
        push!(extra_lines, "    encoder a coalgebra morphism (structure-preserving map). -/")
        push!(extra_lines, "theorem jepa_exact_implies_coalgebra_morphism")
        push!(extra_lines, "    (h : ∀ l ∈ exportedArtifact.losses, l.value = 0) :")
        push!(extra_lines, "    exportedArtifact.CoalgebraExact := by")
        push!(extra_lines, "  exact LoweringArtifact.coalgebra_exact_of_zero_loss h")
        push!(extra_lines, "")
    end

    # Bisimulation declarations
    if !isempty(bisimulations)
        push!(extra_lines, "-- Bisimulation declarations")
        for (name, b) in bisimulations
            push!(extra_lines, "def bisim_$(name) : BisimulationDecl := {")
            push!(extra_lines, "  name := $(lean_string(String(name))),")
            push!(extra_lines, "  coalgebraA := $(lean_string(String(b.coalgebra_a))),")
            push!(extra_lines, "  coalgebraB := $(lean_string(String(b.coalgebra_b))),")
            push!(extra_lines, "  relation := $(lean_string(String(b.relation)))")
            push!(extra_lines, "}")
            push!(extra_lines, "")
        end

        push!(extra_lines, "/-- Two coalgebras are bisimilar iff they map to the same element")
        push!(extra_lines, "    in the final coalgebra — behavioral equivalence. -/")
        push!(extra_lines, "theorem bisimilar_iff_final_coalgebra_equal")
        push!(extra_lines, "    (A B : CoalgebraDecl) (R : BisimulationDecl)")
        push!(extra_lines, "    (h : R.isBisimulation A B) :")
        push!(extra_lines, "    A.finalImage = B.finalImage :=")
        push!(extra_lines, "  CoalgebraDecl.bisim_implies_final_eq h")
        push!(extra_lines, "")
    end

    # Energy function declarations
    energy_fns = get_energy_functions(D)
    if !isempty(energy_fns)
        push!(extra_lines, "-- Energy function declarations")
        for (name, ef) in energy_fns
            push!(extra_lines, "def energy_$(name) : EnergyDecl := {")
            push!(extra_lines, "  name := $(lean_string(String(name))),")
            push!(extra_lines, "  domain := $(lean_list([lean_string(String(d)) for d in ef.domain])),")
            push!(extra_lines, "  energyType := $(lean_string(String(ef.energy_type)))")
            push!(extra_lines, "}")
            push!(extra_lines, "")
        end

        push!(extra_lines, "/-- Energy functions are non-negative for L2 and cosine types. -/")
        push!(extra_lines, "theorem energy_nonneg (e : EnergyDecl)")
        push!(extra_lines, "    (h : e.energyType ∈ [\"l2\", \"cosine\"]) :")
        push!(extra_lines, "    0 ≤ e.evaluate := by")
        push!(extra_lines, "  exact EnergyDecl.nonneg_of_standard h")
        push!(extra_lines, "")
    end

    # Insert before end namespace
    if !isempty(extra_lines)
        lines = split(base_cert, "\n")
        insert_idx = findlast(l -> startswith(l, "end "), lines)
        if insert_idx !== nothing
            result_lines = vcat(lines[1:insert_idx-1], extra_lines, [lines[insert_idx]])
            return join(result_lines, "\n")
        end
    end

    base_cert
end
